spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itmo
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    consumer:
      client-id: itmo-server-client
      group-id: group
      enable-auto-commit: true
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


param:
  env:
    value: ${ENV_PARAM:123}

kafka:
  topics:
    notification: itmo